# Type stubs to help VS Code understand TensorFlow types
from typing import Any, Optional, Tuple, List
import numpy as np

class Model:
    def predict(self, x: np.ndarray) -> np.ndarray: ...
    def fit(self, *args, **kwargs) -> Any: ...
    def evaluate(self, *args, **kwargs) -> Tuple[float, float]: ...
    def save(self, filepath: str) -> None: ...
    def summary(self) -> None: ...
    @property
    def input_shape(self) -> Tuple[Optional[int], ...]: ...

def load_model(filepath: str) -> Model: ...

class Sequential(Model):
    def __init__(self, layers: List[Any] = None): ...
    def add(self, layer: Any) -> None: ...
    def compile(self, optimizer: Any = None, loss: Any = None, metrics: List[str] = None) -> None: ...
