# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  max_batch_size: 10

# Model Configuration
model:
  path: "app/chest_xray_model.keras"
  input_size: [224, 224]
  threshold: 0.5

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Security Configuration
security:
  max_file_size: 10485760  # 10MB in bytes
  allowed_extensions: [".jpg", ".jpeg", ".png"]
